coverage:
  range: "0...100"

  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: 90%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files"
  require_changes: no
