name: "CI"
on:
  push:
    branches: "*"
  pull_request:
env:
  cache-version: 1
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Cache NPM dependencies"
        uses: actions/cache@v4
        with:
          path: |
            "~/.npm"
            "~/.cache/puppeteer"
          key: npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
          restore-keys: |
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-

      - name: "Install NPM dependencies"
        run: |
          npm ci

      - name: "Build"
        run: |
          npm run build

      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: "docs"
          path: docs

      - name: Prepare webpack-stats dir
        run: |
          mkdir relative-ci-artifacts
          cp dist/webpack-stats.* relative-ci-artifacts/

      - name: Upload webpack-stats
        uses: actions/upload-artifact@v4
        with:
          name: relative-ci-artifacts
          path: relative-ci-artifacts

  get-playwright-version:
    name: 'Get Playwright Version'
    runs-on: ubuntu-latest
    outputs:
      playwright-version: ${{ steps.extract_playwright_version.outputs.playwright-version }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Extract @playwright/test version"
        id: extract_playwright_version
        run: |
          playwright_version=$(node -e 'console.log(require("./package-lock.json")["packages"]["node_modules/@playwright/test"].version)')
          echo "playwright-version=$playwright_version" >> $GITHUB_OUTPUT

  test:
    name: "Test"
    runs-on: ubuntu-latest
    needs: get-playwright-version
    container:
      image: mcr.microsoft.com/playwright:v${{ needs.get-playwright-version.outputs.playwright-version }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Cache NPM dependencies"
        uses: actions/cache@v4
        with:
          path: "~/.npm"
          key: npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
          restore-keys: |
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-

      - name: "Install NPM dependencies"
        run: |
          npm ci

      - name: "Run tests"
        run: |
          npm run test
        env:
          HOME: /root

      - name: "Upload coverage results"
        uses: coverallsapp/github-action@v2.3.6

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-jquery-${{ matrix.jquery-version }}
          path: playwright-report/
          retention-days: 30

  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Cache NPM dependencies"
        uses: actions/cache@v4
        with:
          path: |
            "~/.npm"
            "~/.cache/puppeteer"
          key: npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
          restore-keys: |
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-

      - name: "Install NPM dependencies"
        run: |
          npm ci

      - name: "Lint"
        run: |
          npm run lint
