name: "CI"
on:
  push:
    branches: "*"
  pull_request:
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Setup node"
        uses: actions/setup-node@v1
      - name: "Cache NPM dependencies"
        uses: actions/cache@v2
        with:
          path: "~/.npm"
          key: npm-dependencies-${{ runner.os }}-${{ hashFiles('package.json') }}
          restore-keys: |
            npm-dependencies-${{ runner.os }}-${{ hashFiles('package.json') }}
            npm-dependencies-${{ runner.os }}-
      - name: "Install NPM dependencies"
        run: |
          npm ci
      - name: "Build"
        run: |
          npm run build
      - name: "Upload artifact"
        uses: actions/upload-artifact@v2
        with:
          name: "build-artifact"
          path: dist
  test:
    name: "Test"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Setup node"
        uses: actions/setup-node@v1
      - name: "Cache NPM dependencies"
        uses: actions/cache@v2
        with:
          path: "~/.npm"
          key: npm-dependencies-${{ runner.os }}-${{ hashFiles('package.json') }}
          restore-keys: |
            npm-dependencies-${{ runner.os }}-${{ hashFiles('package.json') }}
            npm-dependencies-${{ runner.os }}-
      - name: "Install NPM dependencies"
        run: |
          npm ci
      - name: "Download build artifact"
        uses: actions/download-artifact@v2
        with:
          name: "build-artifact"
          path: dist
      - name: "Test"
        run: |
          npm run test
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Setup node"
        uses: actions/setup-node@v1
      - name: "Cache NPM dependencies"
        uses: actions/cache@v2
        with:
          path: "~/.npm"
          key: npm-dependencies-${{ runner.os }}-${{ hashFiles('package.json') }}
          restore-keys: |
            npm-dependencies-${{ runner.os }}-${{ hashFiles('package.json') }}
            npm-dependencies-${{ runner.os }}-
      - name: "Install NPM dependencies"
        run: |
          npm ci
      - name: "Lint"
        run: |
          npm run lint
