---
name: "Deploy docs"
"on":
  push:
    branches: "master"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  cache-version: 1

jobs:
  build:
    name: "Build docs"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v7

      - name: "Configure Pages"
        uses: actions/configure-pages@v5

      - name: "Cache NPM dependencies"
        uses: actions/cache@v6
        with:
          path: "~/.npm"
          key: >-
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{
            hashFiles('package.json') }}
          restore-keys: |
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-

      - name: "Install NPM dependencies"
        run: |
          npm ci

      - name: "Build docs"
        run: |
          npm run build:docs

      - name: "Upload artifact"
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs"

  deploy:
    name: "Deploy docs"
    needs: "build"
    runs-on: ubuntu-latest
    environment:
      name: "github-pages"
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: "Deploy to GitHub Pages"
        id: "deployment"
        uses: actions/deploy-pages@v4
