name: "Deploy"
on:
  push:
    branches:
      - master
env:
  cache-version: 1

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup node"
        uses: actions/setup-node@v3.8.1

      - name: "Cache NPM dependencies"
        uses: actions/cache@v3
        with:
          path: "~/.npm"
          key: npm-dependencies-${{ runner.os }}-${{ hashFiles('package.json') }}
          restore-keys: |
            npm-dependencies-${{ runner.os }}-${{ hashFiles('package.json') }}
            npm-dependencies-${{ runner.os }}-

      - name: "Install NPM dependencies"
        run: |
          npm ci

      - name: "Build"
        run: |
          npm run build

      - name: "Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: "demo-page"
          path: docs

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Download artifact"
        uses: actions/download-artifact@v3
        with:
          name: "demo-page"
          path: docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: docs
          clean: true
          single-commit: true
