name: "Deploy docs"
on:
  push:
    branches:
      - master
env:
  cache-version: 1
jobs:
  build:
    name: "Build docs"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Cache NPM dependencies"
        uses: actions/cache@v4
        with:
          path: "~/.npm"
          key: npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
          restore-keys: |
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-

      - name: "Install NPM dependencies"
        run: |
          npm ci

      - name: "Build docs"
        run: |
            npm run build:docs

      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: "docs"
          path: docs

  deploy:
    name: "Deploy docs"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Download artifact"
        uses: actions/download-artifact@v4
        with:
          name: "docs"
          path: docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.3
        with:
          branch: gh-pages
          folder: docs
          clean: true
          single-commit: true
